# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zn.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OtherWindow(object):
    def setupUi(self, OtherWindow):
        OtherWindow.setObjectName("OtherWindow")
        OtherWindow.resize(488, 293)
        OtherWindow.setStyleSheet("background-color: rgb(255, 248, 250);")
        self.centralwidget = QtWidgets.QWidget(OtherWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.send_Text_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.send_Text_6.setGeometry(QtCore.QRect(90, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.send_Text_6.setFont(font)
        self.send_Text_6.setStyleSheet("QTextEdit {\n"
"    border: 0.5px solid black;\n"
"    border-radius: 2px;\n"
"\n"
"}\n"
"")
        self.send_Text_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.send_Text_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.send_Text_6.setObjectName("send_Text_6")
        self.port_text_15 = QtWidgets.QLabel(self.centralwidget)
        self.port_text_15.setGeometry(QtCore.QRect(40, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.port_text_15.setFont(font)
        self.port_text_15.setObjectName("port_text_15")
        self._Kd = QtWidgets.QTextBrowser(self.centralwidget)
        self._Kd.setGeometry(QtCore.QRect(380, 140, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self._Kd.setFont(font)
        self._Kd.setStyleSheet("QTextEdit {\n"
"    border: 0.5px solid black;\n"
"    border-radius: 2px;\n"
"\n"
"}\n"
"")
        self._Kd.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self._Kd.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self._Kd.setObjectName("_Kd")
        self.Fill_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Fill_Button.setGeometry(QtCore.QRect(240, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Fill_Button.setFont(font)
        self.Fill_Button.setStyleSheet("")
        self.Fill_Button.setObjectName("Fill_Button")
        self.port_text_20 = QtWidgets.QLabel(self.centralwidget)
        self.port_text_20.setGeometry(QtCore.QRect(200, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.port_text_20.setFont(font)
        self.port_text_20.setObjectName("port_text_20")
        self.Ti = QtWidgets.QTextBrowser(self.centralwidget)
        self.Ti.setGeometry(QtCore.QRect(240, 60, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Ti.setFont(font)
        self.Ti.setStyleSheet("QTextEdit {\n"
"    border: 0.5px solid black;\n"
"    border-radius: 2px;\n"
"\n"
"}\n"
"")
        self.Ti.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Ti.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Ti.setObjectName("Ti")
        self.port_text_19 = QtWidgets.QLabel(self.centralwidget)
        self.port_text_19.setGeometry(QtCore.QRect(170, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.port_text_19.setFont(font)
        self.port_text_19.setObjectName("port_text_19")
        self.port_text_17 = QtWidgets.QLabel(self.centralwidget)
        self.port_text_17.setGeometry(QtCore.QRect(340, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.port_text_17.setFont(font)
        self.port_text_17.setObjectName("port_text_17")
        self._Ki = QtWidgets.QTextBrowser(self.centralwidget)
        self._Ki.setGeometry(QtCore.QRect(380, 100, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self._Ki.setFont(font)
        self._Ki.setStyleSheet("QTextEdit {\n"
"    border: 0.5px solid black;\n"
"    border-radius: 2px;\n"
"\n"
"}\n"
"")
        self._Ki.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self._Ki.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self._Ki.setObjectName("_Ki")
        self.port_text_18 = QtWidgets.QLabel(self.centralwidget)
        self.port_text_18.setGeometry(QtCore.QRect(340, 140, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.port_text_18.setFont(font)
        self.port_text_18.setObjectName("port_text_18")
        self.port_text_21 = QtWidgets.QLabel(self.centralwidget)
        self.port_text_21.setGeometry(QtCore.QRect(200, 60, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.port_text_21.setFont(font)
        self.port_text_21.setObjectName("port_text_21")
        self.port_text_14 = QtWidgets.QLabel(self.centralwidget)
        self.port_text_14.setGeometry(QtCore.QRect(40, 60, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.port_text_14.setFont(font)
        self.port_text_14.setObjectName("port_text_14")
        self._Kp = QtWidgets.QTextBrowser(self.centralwidget)
        self._Kp.setGeometry(QtCore.QRect(380, 60, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._Kp.sizePolicy().hasHeightForWidth())
        self._Kp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self._Kp.setFont(font)
        self._Kp.setStyleSheet("QTextEdit {\n"
"    border: 0.5px solid black;\n"
"    border-radius: 2px;\n"
"\n"
"}\n"
"")
        self._Kp.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self._Kp.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self._Kp.setObjectName("_Kp")
        self.send_Text_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.send_Text_5.setGeometry(QtCore.QRect(90, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.send_Text_5.setFont(font)
        self.send_Text_5.setStyleSheet("QTextEdit {\n"
"    border: 0.5px solid black;\n"
"    border-radius: 2px;\n"
"\n"
"}\n"
"")
        self.send_Text_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.send_Text_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.send_Text_5.setObjectName("send_Text_5")
        self.Td = QtWidgets.QTextBrowser(self.centralwidget)
        self.Td.setGeometry(QtCore.QRect(240, 100, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Td.setFont(font)
        self.Td.setStyleSheet("QTextEdit {\n"
"    border: 0.5px solid black;\n"
"    border-radius: 2px;\n"
"\n"
"}\n"
"")
        self.Td.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Td.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Td.setObjectName("Td")
        self.Cal_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Cal_Button.setGeometry(QtCore.QRect(90, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Cal_Button.setFont(font)
        self.Cal_Button.setStyleSheet("")
        self.Cal_Button.setObjectName("Cal_Button")
        self.port_text_16 = QtWidgets.QLabel(self.centralwidget)
        self.port_text_16.setGeometry(QtCore.QRect(340, 60, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.port_text_16.setFont(font)
        self.port_text_16.setObjectName("port_text_16")
        OtherWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OtherWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 488, 26))
        self.menubar.setObjectName("menubar")
        OtherWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OtherWindow)
        self.statusbar.setObjectName("statusbar")
        OtherWindow.setStatusBar(self.statusbar)

        self.retranslateUi(OtherWindow)
        QtCore.QMetaObject.connectSlotsByName(OtherWindow)

    def retranslateUi(self, OtherWindow):
        _translate = QtCore.QCoreApplication.translate
        OtherWindow.setWindowTitle(_translate("OtherWindow", "MainWindow"))
        self.port_text_15.setText(_translate("OtherWindow", "Pcr:"))
        self.Fill_Button.setText(_translate("OtherWindow", "Fill"))
        self.port_text_20.setText(_translate("OtherWindow", "Td:"))
        self.port_text_19.setText(_translate("OtherWindow", "Ziegler - Nichols 2"))
        self.port_text_17.setText(_translate("OtherWindow", "Ki:"))
        self.port_text_18.setText(_translate("OtherWindow", "Kd:"))
        self.port_text_21.setText(_translate("OtherWindow", "Ti:"))
        self.port_text_14.setText(_translate("OtherWindow", "Kcr:"))
        self.Cal_Button.setText(_translate("OtherWindow", "Calculate"))
        self.port_text_16.setText(_translate("OtherWindow", "Kp:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OtherWindow = QtWidgets.QMainWindow()
    ui = Ui_OtherWindow()
    ui.setupUi(OtherWindow)
    OtherWindow.show()
    sys.exit(app.exec_())
